### ISSUE TITLE
Menu navigation

### ISSUE THREAD

**Issue by mikemccamon** [scorchingoyster/owasp-layout#23]
Reduce line height by ~1/2. I think there's too much space between menues

**Comment by scorchingoyster** [comment]
1/2 seems a little too narrow (left)

I suggest a 2/3 change (right) to make scanning menu names a little easier, what do you think @mikemccamon?

![image](https://user-images.githubusercontent.com/3586992/61176829-a6e13d00-a595-11e9-81d3-f871a73255bc.png)
