### ISSUE TITLE
Member list reduce vetical spacing of logo.  Seems 1/3 too tall

### ISSUE THREAD

**Issue by mikemccamon** [scorchingoyster/owasp-layout#30]

**Comment by scorchingoyster** [comment]
I changed it from 10px to 6px, but I wanted to let you know that I originally gave it that much space to prevent edge cases where the logos would be too close with each other vertically, like in the case of UPS logo siding with another tall logo—worth noting that I already I added transparent area around the image to make it take up less space, too.

![image](https://user-images.githubusercontent.com/3586992/61176631-3127a200-a592-11e9-8f65-8aea3b8a8588.png)


I just decided to increase the transparent area a bit more on taller logos images, so let me know if you'd like to see this tweaked further.
