### ISSUE TITLE
OPTIONAL: Logo in spotlight company

### ISSUE THREAD

**Issue by mikemccamon** [scorchingoyster/owasp-layout#31]
One way to get around the Company Name then right below logo as a name would be to put the logo under the copy on a new line and right justify. Not a requirement, just an idea.

**Comment by scorchingoyster** [comment]
it looks like this in practice:

![image](https://user-images.githubusercontent.com/3586992/61224456-9becf080-a6ec-11e9-87d7-2c4445ed3d51.png)

**Comment by mikemccamon** [comment]
This has been resolved
