### ISSUE TITLE
Project tab "selected region"

### ISSUE THREAD

**Issue by mikemccamon** [scorchingoyster/owasp-layout#38]
When I visit the project page. Then start clicking the submenus eventually the submenu copy gets "selected" with a blue border around it.

**Comment by scorchingoyster** [comment]
yup, I noticed that. think was some side-effect of the new script. will fix.

**Comment by scorchingoyster** [comment]
just to verify: you noticed this while using Chrome or Safari, correct?

**Comment by mikemccamon** [comment]
Chrome is all I’ve got when it comes to desktop


Mike McCamon | m: +1.913.940.2737 | Sent from iPhone

**Comment by scorchingoyster** [comment]
sure. just wanted to double check which browser rendering engine might caused it.

**Comment by scorchingoyster** [comment]
it was triggered by WebKit-based browsers user agent stylesheet, treating it as an interactive element when it isn't, which has to do with accessibility support (tabbing through items in a page).

after taking some time to read more about it (also as a part of research for #5), I think it's safe to modify it for now, so you won't be seeing an outline anymore. I have added a comment in the CSS fix just in case that this might become an issue down the road.
