### ISSUE TITLE
Move Corporate Spotlight to Left and Members to Right

### ISSUE THREAD

**Issue by mikemccamon** [scorchingoyster/owasp-layout#41]
This way on mobile the Spotlight will be first.

**Comment by scorchingoyster** [comment]
If you'd like to keep them in their current sequence on desktop, I can specify that the sequence is reversed for mobile. If not, I can just do as you suggested.

**Comment by mikemccamon** [comment]
We all read left to right and I think it's a good idea to have Spotlight on left - and we get mobile love for free.
