### ISSUE TITLE
Main Menu on Desktop Demarcation

### ISSUE THREAD

**Issue by mikemccamon** [scorchingoyster/owasp-layout#43]
the header needs some sort of demarcation (bar/rule/graphic/shading/etc) to set it apart from the rest of the page. We do this on mobile, just not on desktop.

**Comment by scorchingoyster** [comment]
How is this? Similar treatment like on mobile, but with a light dropshadow. 

![firefox_JsbS5D6Hqc](https://user-images.githubusercontent.com/3586992/63554380-4e457e00-c50b-11e9-9ac2-0771e5c27602.png)

**Comment by mikemccamon** [comment]
Like it
