### ISSUE TITLE
Reduce vertical spacing on submenus

### ISSUE THREAD

**Issue by mikemccamon** [scorchingoyster/owasp-layout#45]
Check out how "loaded" menus look on https://www2.owasp.org/  Need more compact vertical line spacing.

**Comment by scorchingoyster** [comment]
It's a little heavy. I think I will tweak both the line-spacing and the font-size to get them look more breathable—it seems to occupy a lot of vertical space when expanded as well, so that should help.

**Comment by mikemccamon** [comment]
Sounds great!

**Comment by scorchingoyster** [comment]
How is this? About 20% reduction in height; I changed the font-weight but lowered the size, and then decreased the vertical spacing.

Also showing the submenu separator at the bottom for #46.

![i_view64_POqkEHhfUL](https://user-images.githubusercontent.com/3586992/63553890-d62a8880-c509-11e9-837a-3bc876e3efaf.png)

**Comment by mikemccamon** [comment]
For some reason the font is not less readable in the picture on the right. I'm almost thinking that just reducing the line spacing on left would get us there. (Also looks like font on right is bold now(?)  I liked your original selections just not so much negative space in line spacing IMHO
