### ISSUE TITLE
Mobile menu close button doesn't work

### ISSUE THREAD

**Issue by scorchingoyster** [scorchingoyster/owasp-layout#49]

**Comment by scorchingoyster** [comment]
Unsure what's going on here. Compared my old code with the current version and there doesn't seem to be anything that should get in the way of script, but it was as if the script couldn't detect the close action (toggling to hide the mobile menu pane).

I suspect it might have something to do with the new menu generating scripts that Harold added in and how it interacts with the existing JS.

**Comment by hblankenship** [comment]
I agree - it has something to do with my changes.  That's actually one of
the items I have on my to do list.  :)


Harold L. Blankenship

OWASP Foundation

Director of Technology and Projects

Join us in September at Global AppSec DC
<https://dc.globalappsec.org/> or Global
AppSec Amsterdam <https://ams.globalappsec.org/>!

<https://www.globalappsec.org/>
